export * from './user.model';
export * from './student.model';
export * from './teacher.model';
export * from './class.model';
export * from './subject.model';
export * from './teacher-subject.model';
export * from './enrollment.model';
export * from './attendance.model';
export * from './exam.model';
export * from './fee.model';
export * from './timetable.model';
export * from './announcement.model';
// export * from './grade.model';
export * from './audit-log.model';